[package]
name = "alkomp"
version = "0.1.0"
authors = ["RustyBamboo <d@volya.xyz>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
wgpu = "0.6"
futures = "*"
colored = "*"
bytemuck = "*"
shaderc = { version = "0.6.2", optional = true}
ndarray = {version = "*", features = []}