[package]
name = "vulkomp"
version = "0.1.0"
authors = ["daniel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.6"
futures = "*"
colored = "*"
bytemuck = "*"
shaderc = { version = "0.6.2" }